image:
  file: .gitpod.Dockerfile
checkoutLocation: '.'

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - name: connect
    # The private SSH key is stored in a single line as DBT_SNOWFLAKE_PRIVATE_KEY. Unfortunately,
    # Snowflake will only accept the key if it is multi-line. The sed command transforms the key
    # and then stores it as a file, which can be processed by Snowflake.    
    # command: |
    #   echo "${DBT_SNOWFLAKE_PRIVATE_KEY}" | sed -e "s/-----BEGIN PRIVATE KEY-----/&\n/" -e "s/-----END PRIVATE KEY-----/\n&/" -e "s/\S\{64\}/&\n/g" > $GITPOD_REPO_ROOT/profiles/private_key.p8
    command: |
      dbt debug
      dbt deps
    openMode: split-left
  - name: generate docs
    command: |
      dbt docs generate
      dbt docs serve --no-browser --port 8080
    openMode: split-right

vscode:
  extensions:
    - ms-python.python
    - mechatroner.rainbow-csv
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - koszti.snowflake-driver-for-sqltools
    - innoverio.vscode-dbt-power-user
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - samuelcolvin.jinjahtml

# github:
#   prebuilds:
#     master: true
#     branches: true
#     pullRequests: true
#     pullRequestsFromForks: false
#     addCheck: true
#     addComment: false
#     addBadge: false